name: Generate Resources & Deploy GitHub Pages
on:
  push:
    branches:
      - master
      - Dev
jobs:
  GenerateResource:
    runs-on: windows-latest

      # Only when run from the main repo
    if: github.repository == 'microsoft/Microsoft365DSC'

    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        shell: powershell
        run: |
          git clone https://github.com/PowerShell/DscResource.Tests
          Import-Module -Name "./DscResource.Tests/AppVeyor.psm1"
          Invoke-AppveyorInstallTask
          $env:APPVEYOR_BUILD_FOLDER = Get-Location | select -ExpandProperty Path
          $env:APPVEYOR_BUILD_VERSION = "1.0.0"
          Invoke-AppveyorAfterTestTask `
               -Type 'Wiki' `
               -MainModulePath 'Modules\Microsoft365DSC' `
               -ResourceModuleName 'Microsoft365DSC'
      - name: Extract some files
        run: 7z x Microsoft365DSC_1.0.0_wikicontent.zip
      - name: Copy AAD Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\AAD*.md -Destination $executingScriptDirectory\docs\docs\resources\azure-ad\ -force
      - name: Copy EXO Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\EXO*.md -Destination $executingScriptDirectory\docs\docs\resources\exchange\ -force
      - name: Copy Intune Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\Intune*.md -Destination $executingScriptDirectory\docs\docs\resources\intune\ -force
      - name: Copy office365 Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\O365*.md -Destination $executingScriptDirectory\docs\docs\resources\office365\ -force
      - name: Copy onedrive Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\OD*.md -Destination $executingScriptDirectory\docs\docs\resources\onedrive\ -force
      - name: Copy power-platform Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\PP*.md -Destination $executingScriptDirectory\docs\docs\resources\power-platform\ -force
      - name: Copy planner Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\Planner*.md -Destination $executingScriptDirectory\docs\docs\resources\planner\ -force
      - name: Copy security-compliance Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\SC*.md -Destination $executingScriptDirectory\docs\docs\resources\security-compliance\ -force
      - name: Copy sharepoint Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\SPO*.md -Destination $executingScriptDirectory\docs\docs\resources\sharepoint\ -force
      - name: Copy Teams Files
        run: |
          $executingScriptDirectory = ${Env:GITHUB_WORKSPACE}
          Move-Item -Path $executingScriptDirectory\Teams*.md -Destination $executingScriptDirectory\docs\docs\resources\teams\ -force
      - name: Commit files # commit the output folder
        if: always()
        run: |
          git config --local user.email "nik.charlebois@microsoft.com"
          git config --local user.name "Nik Charlebois"
          git add D:/a/Microsoft365DSC/Microsoft365DSC/docs/docs/resources/*
          git pull
          git commit -m "Add changes"
          git push

  deploy:
    needs: GenerateResource
    runs-on: ubuntu-latest

    # Only when run from the main repo
    if: github.repository == 'microsoft/Microsoft365DSC'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: |
          pip install mkdocs-material
          pip install mkdocs-include-dir-to-nav
      - name: Deploy
        working-directory: ./docs
        run: mkdocs gh-deploy --force
